services:
  - type: web
    name: kitoblar-miniapp
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BOOK_CLUB_CHAT_LINK
        sync: false
      - key: DB_PATH
        value: /var/data/books.db
    disk:
      name: kitoblar-data
      mountPath: /var/data
      sizeGB: 1
